version: "3.3"

services:
    backend:
      image: gerrome/django-react2_backend:1
    #  build:
    #      context: ./backend
      volumes:
        - .:/app
        - static_volume:/app/staticfiles/
      expose:
        - 8000
      depends_on:
        - db

    db:
      image: postgres:10.1-alpine

    nginx:
      image: gerrome/django-react2_nginx:1
    #  build:
    #      context: ./frontend
      ports:
        - 80:80
      volumes:
        - static_volume:/app/staticfiles/
      depends_on:
        - backend
    
volumes:
   static_volume: 
